version: '3.1'
 
services:
 
  main:
    image: localhost:5000/irods-jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./irods_docker_files:/irods_docker_files
      - ./jenkins_output:/jenkins_output
      - /irods_jenkins_sandbox:/irods_jenkins_sandbox
      - /projects/irods/vsphere-testing/externals/amazon_web_services-CI.keypair:/projects/irods/vsphere-testing/externals/amazon_web_services-CI.keypair
      - /projects/irods/vsphere-testing/externals/mysql-connector-odbc-5.3.7-linux-ubuntu16.04-x86-64bit.tar.gz:/projects/irods/vsphere-testing/externals/mysql-connector-odbc-5.3.7-linux-ubuntu16.04-x86-64bit.tar.gz
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins_home:
  irods_docker_files:
  jenkins_output:
  irods_jenkins_sandbox:
