ARG base_image=ubuntu:16.04
FROM $base_image

ARG database_type="postgres"
ENV DATABASE=$database_type

ARG arg_jenkins_ouput=/worm_hole_missing
ENV JENKINS_OUTPUT=${arg_jenkins_output}

RUN pip install xmlrunner

ADD install_database.py /
RUN chmod u+x /install_database.py

ADD install_externals.py /
RUN chmod u+x /install_externals.py

COPY ci_utilities.py /

RUN echo export IRODS_ENABLE_TEST_MODE="1" > /etc/profile.d/irods.sh
RUN chmod 644 /etc/profile.d/irods.sh

ADD install_and_test.py /
RUN chmod u+x /install_and_test.py

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/sbin/init"]
